---
title: "Twitter's Search algorithm"
author: "Vyanna Hill"
date: "`r Sys.Date()`"

---

### Introduction

For my recommender system of choice, I selected Twitter's search engine. It is one of few social media platforms, where users can choose between types of media in their search results. For example, Users can search through specific types of media (both organic/promoted tweets).

The Tweets can be organized by Users profiles, tweets, pictures and video media, which is blocked in the search results page. Users can also specified where the tweets originated with filtering based on users you follow.

## Scenario Design Analysis

For our target audiences, Any active users on the platform can access the search query. There is a extra benefit towards registered users with their log ins for additional query specifications. For twitter users, They want their tweet to appear as the top results of a query. Twitter users goals is engagement for their profiles show for recommended profiles.

Twitter key goals is fostering tweet engagement on their platform. Results pages automatically loads on the top tweets section on the results pages. Twitter wants users to engage with tweets through likes, re tweets, Quotes and replies. Twitter users goals are building up a following their profiles. They want their tweets to be easily found and can be identified through the thousands of tweets at the moment.

#### Reverse Engineer 

We can take a look at twitter's available API to view Twitter's key goals! In the API provided, The standard query requires only the query string and the optional specifications like locale, the recency of the tweets, its result type and etc. The results type is particular important for twitter users, as its insertion can determine if the users tweets will be seen first.

```{}
$ curl --request GET 
 --url 'https://api.twitter.com/1.1/search/tweets.json?q=nasa&result_type=popular' 
 --header 'authorization: OAuth oauth_consumer_key="consumer-key-for-app", 
...
$ twurl /1.1/search/tweets.json?q=nasa&result_type=popular
```

There are three types of results types: Recent, Popular, mixed. From the Json request above, a user can specified if the tweets are looking for are  popular from high engagement or the most recent tweets. Twitter users drives for a breakthrough on the most popular tag. The tweets are most likely to stay passed when it is no longer recent unlike most recent tweets. In addition, Popular users are ranked higher in the search results page as Twitter algorithms favors users with high engagement and their activity on its platform^[https://sproutsocial.com/insights/twitter-algorithm/]. We can see a example of the ranking with a snippet of the Json response of a resulted tweet. 

```{}
"protected": false,
"followers_count": 2566921,
"favourites_count": 1281,
"verified": true,
```

Each tweet carries a identifier tags of its relevancy. The Twitter visibility increases if their profile has higher Followers/Favorites count and if they have a verified profile^[https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets].


### Recommendations

I want to shift my recommendation towards the other blocking, the Photos and Videos sections. I believe these section lacked granularity as its takes the top tweets sorting approach. The tweets show based on popularity, which only benefits verified/ popular users. Smaller accounts will not break the mold in its current  blocking compared to the mixed result type found in recent tweets.

Twitter will benefit from this recommendation, as smaller accounts have a better aspect of community. They engage more frequently between each other, where Twitter can have more cleaner targeting for advertisers.

